# Generated by Django 2.1.9 on 2019-06-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CachedSubmissionIds',
        ),
    ]
