# Generated by Django 2.1.9 on 2019-07-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='graph_end_point',
            new_name='end_point',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='graph_slug',
            new_name='slug',
        ),
    ]
