# Generated by Django 2.1.9 on 2019-07-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190701_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='chart_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='chart',
            name='slug',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
