# Generated by Django 2.1.10 on 2019-07-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chart_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(choices=[('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('radar_chart', 'Radar Chart'), ('constant_value', 'Constant Value'), ('donut_chart', 'Donut Chart')], max_length=128),
        ),
    ]
