# Generated by Django 2.1.10 on 2019-07-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190707_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(choices=[('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('radar_chart', 'Radar Chart'), ('constant_value', 'Constant Value'), ('donut_chart', 'Donut Chart'), ('polar_chart', 'Polar Chart')], max_length=128),
        ),
    ]
