# Generated by Django 2.1.9 on 2019-07-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190715_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(choices=[('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('radar_chart', 'Radar Chart'), ('constant_value', 'Constant Value'), ('donut_chart', 'Donut Chart'), ('polar_chart', 'Polar Chart'), ('multiple_statistics', 'Multiple Statistics'), ('product_line', 'Product Line')], max_length=128),
        ),
    ]
