# Generated by Django 2.1.9 on 2019-06-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='caq_ncr',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
