# Generated by Django 2.1.9 on 2019-06-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20190617_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineclassification',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
