# Generated by Django 2.1.9 on 2019-06-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20190617_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedetails',
            name='summary',
        ),
    ]
