# Generated by Django 2.1.9 on 2019-06-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_auto_20190618_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='draft',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
