# Generated by Django 2.1.9 on 2019-06-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_submission_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='submission',
            name='scan_qr_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
