# Generated by Django 2.1.9 on 2019-06-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_auto_20190620_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='serial_number',
            field=models.CharField(blank=True, max_length=576, null=True),
        ),
    ]
