# Generated by Django 2.1.9 on 2019-06-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_auto_20190620_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=168)),
                ('graph_type', models.CharField(max_length=128)),
            ],
        ),
    ]
