# Generated by Django 2.1.9 on 2019-07-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_graph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graph',
        ),
    ]
